### ISSUE TITLE
state management

### ISSUE THREAD

**Issue by bugzpodder** [Py4Js/pyscript-react#1068]
### What happened?

I spent a bunch of time trying to get PyScript to work in react and had a lot of double rendering issues, so I ended up doing just:

```
  const store = usePyScriptStore();
  const id = useId();
  useLayoutEffect(() => {
      store.pyScript?.interpreter.run(code, id).then(() => {
          setIsLoading(false);
        });
    }, [...]);
``` 

as my own PyScript component and that worked flawlessly

### Version

1.0.0

### How to reproduce?

Click chrome.exe

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KrzysztofZawisla** [comment]
Hi, 

right now to use the default PyScript store integrated into the package you need to use PyScriptProviderZustandWrapper. Sorry for the lack of documentation, but we are trying to release it as fast as possible. The behavior of usePyScriptStore is that it starts with null as an empty value indicator. After that as fast as PyScriptProviderZustandWrapper is mounted it starts to check for pyscript to be registered under the Window object. The interval of that is 10ms. The first render should be with pyscript as a null value and the next one should have a valid object.

Best Regards

**Comment by KrzysztofZawisla** [comment]
@ShootGan

**Comment by bugzpodder** [comment]
Yes I was already using PyScriptProviderZustandWrapper, that's fine.
I needed my own PyScript implementation, putting it here for reference:

```
const PyScript = memo(function PyScript({ context, id, code, errorDisplay }: PyScriptProps) {
  const [loading, setIsLoading] = useState(false);
  const [error, setError] = useState("");
  const store = usePyScriptStore();
  const pyScriptId = useMemo(() => (id ? `py-script-${id}` : undefined), [id]);
  useEffect(() => {
    async function exec() {
      try {
        // set context here
        await store.pyScript?.interpreter.run(code, id).then(() => {
          setIsLoading(false);
        });
      } catch (e) {
        setError(String(e));
      }

      setIsLoading(false);
    }
    if (pyScriptId && code) {
      setPyScriptContext(pyScriptId, context);
      setIsLoading(true);
      setError("");
      exec();
    }
  }, [code, context, pyScriptId, store]);

  if (!id) {
    return null;
  }

  return (
    <div>
      {loading && "Loading..."}
      {error && (<pre>{error}</pre>)}
      <div key={pyScriptId} id={pyScriptId} />
    </div>
  );
});
```
