### ISSUE TITLE
[Bug]: pyscript fetch is not an array

### ISSUE THREAD

**Issue by bugzpodder** [Py4Js/pyscript-react#1069]
### What happened?

[fetch should be array](https://docs.pyscript.net/latest/tutorials/py-config-fetch.html)
https://docs.pyscript.net/latest/reference/elements/py-config.html#mixing-inline-and-file-based-configs

### Version

1.0.0

### How to reproduce?

Click chrome.exe

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kaurelia** [comment]
#1070
