### ISSUE TITLE
[Bug]: Component not rendering pyscript results

### ISSUE THREAD

**Issue by ChandraPranjal** [Py4Js/pyscript-react#1500]
### What happened?

This is my App react component. Browser is not displaying it's result
App.js -> [https://github.com/ChandraPranjal/py-script-react-/blob/master/src/App.js](https://github.com/ChandraPranjal/py-script-react-/blob/master/src/App.js)

I've tried adding/removing 

```
 <link rel="stylesheet" href="https://pyscript.net/latest/pyscript.css" />
  <Script defer src="https://pyscript.net/latest/pyscript.js" strategy='beforeInteractive' />
```

in index.html still can't see results on browser

I've noticed that py-script provider is translating as 
`<py-script code="print('Hello World!')" id="py-internal-0"></py-script>`

You can check full configuration at -> https://github.com/ChandraPranjal/py-script-react-/tree/master
Installation : 

`npm i zustand react-helmet-async pyscript-react
`
![image](https://github.com/Py4Js/pyscript-react/assets/96934491/cfb97e51-0d36-4516-b031-4c6e184aede8)

What's the solution ? 

### Version

v0.0.4

### How to reproduce?

Click chrome.exe

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ChandraPranjal** [comment]
Well, I fixed it like this 

```
import React from 'react'; // Import React
import './App.css';
import PyScript from "pyscript-react/esm"; // main entrypoint
import PyScriptProvider from "pyscript-react/esm/components/py-script-provider"; // specific component
function App() {
  return (
    <div className="App">
      <PyScriptProvider>
        <py-config>
          packages = ["cryptography", "pycryptodome"]
        </py-config>
        <PyScript>
            
        {`
            print("Hello World")
            print("Hello World")
            print("Hello World")
            print("Hello World")
          `}
            
        </PyScript>
      </PyScriptProvider>
    </div>
  );
}

export default App;
```

Different syntax unlike described in  documentation

**Comment by KrzysztofZawisla** [comment]
Hi @ChandraPranjal,

our library doesn't have full documentation on how to use our components, and we apologize for that. It will be added in the future, as time will allow us to do that. The `PyScript` component takes Python code to execute in two different ways. The first one is by passing it as a string to the child, which is not the preferred way to do that. The second one is by using the `source` property or `src` (its alias) by pointing to a Python file that served from the public directory. You can optimize your solution by importing PyScript from "pyscript-react/esm/components/py-script". It will allow you to uninstall Zustand, because when you are importing from the main entry point of the library it requires all peer dependencies even if they are not used. The second thing is that you can delete your py-config tag and pass packages by the `PyScript` component by `pyConfigProps`.

Changed version

```tsx
import React from 'react'; // Import React <- you can configure bundler to use automatic runtime and delete this statement
import './App.css';
import PyScript from "pyscript-react/esm/components/py-script"; // main entrypoint
import PyScriptProvider from "pyscript-react/esm/components/py-script-provider"; // specific component

function App() {
  return (
    <div className="App">
      <PyScriptProvider>
        <PyScript pyConfigProps={{
packages: new Set(["cryptography", "pycryptodome"])
}}>
        {`
            print("Hello World")
            print("Hello World")
            print("Hello World")
            print("Hello World")
          `}
        </PyScript>
      </PyScriptProvider>
    </div>
  );
}

export default App;
```

**Comment by KrzysztofZawisla** [comment]
You can also highlight python code syntax with this extension directly in JavaScript/TypeScript if you are using Visual Studio Code.

https://marketplace.visualstudio.com/items?itemName=bierner.comment-tagged-templates

https://imgur.com/a/SCV24g0

**Comment by ChandraPranjal** [comment]
First of all thanks for this lib. I've finding it quite useful in my project. 
I understand time/effort constrained for writing complete documentation, but is there any way I can at least know functions to use. 

Secondly, I need one more help 
let's say i've a react useState "name" / or maybe` var` "name", 
I want to set it in inside `PyScript` component .

How can I do that ? 
```

import React, { useState } from 'react';
import './App.css';
import PyScript from 'pyscript-react/esm';

function App() {
  const [name, setName] = useState('Hi');

  return (
    <div className="App">
      <button py-click="current_time()" id="get-time" className="py-button">
        Get current time
      </button>
      <p id="current-time"></p>

      <py-config>
        packages = []
      </py-config>
      <PyScript>
        {`
          from pyscript import Element

          //something like this
          setName("OK")
        `}
      </PyScript>

      {/* Render the value of x */}
      <>name</>
    </div>
  );
}

export default App;

```

**Comment by KrzysztofZawisla** [comment]
> but is there any way I can at least know functions to use

for now unfortunately the only way is by checking source code. I will patch documentation and JSDoc comments ASAP. This is one of the reasons why `pyscript-react` is in pre-release version 0.x.

> let's say i've a react useState "name" / or maybe var "name",
> I want to set it in inside PyScript component .

https://docs.pyscript.net/latest/guides/event-handlers.html?highlight=javascript#subscribe-to-event-with-addeventlistener
https://pyodide.org/en/stable/usage/type-conversions.html

It should help you. In general, pyscript uses pyodide under the hood. It's Python compiled into WebAssembly. All pyodide ffi API is valid in pyscript ecosystem. I guess at some point you will need to use also pyodide from JavaScript. You can access it via `usePyScript` hook, or `usePyScriptStore` which is a raw zustand store to store pyscript object. In the case of problems of pyodide interpreter instance on result from hook or store you can use directly it by `window.pyscript.interpreter.interpreter`.

I would like to apologize one more time for the lack of documentation.
